http.host: 0.0.0.0

# Uncomment the following lines for a production cluster deployment
#ransport.host: 0.0.0.0
#discovery.zen.minimum_master_nodes: 1

cluster.name: elasticsearch
node.name: testmaxime
#network.host: 127.0.0.1
#network.bind_host: 0
